# Minimal Camunda Platform configuration with Zeebe, Operate, Elasticsearch, Keycloak, Identity, and Postgres
# This configuration provides:
# - Zeebe: Workflow engine
# - Operate: Process monitoring and history UI
# - Elasticsearch: Process data storage
# - Keycloak & Identity: Authentication for Operate UI
# - Postgres: Database for Keycloak and Identity

services:
  zeebe:
    image: camunda/zeebe:8.3.0
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8088:8080"
    environment:
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    volumes:
      - zeebe:/usr/local/zeebe/data
    networks:
      - camunda-platform
    depends_on:
      - elasticsearch

  operate:
    image: camunda/operate:8.3.0
    container_name: operate
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=identity-auth
      - CAMUNDA_OPERATE_IDENTITY_BASEURL=http://identity:8084
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:18080/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_CLIENTID=operate
      - CAMUNDA_OPERATE_IDENTITY_CLIENTSECRET=XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      - CAMUNDA_OPERATE_IDENTITY_AUDIENCE=operate-api
    volumes:
      - operate_tmp:/tmp
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - elasticsearch
      - identity

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - camunda-platform

  identity:
    image: camunda/identity:8.3.0
    container_name: identity
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - IDENTITY_URL=http://localhost:8084
      - KEYCLOAK_URL=http://keycloak:18080/auth
      - IDENTITY_AUTH_PROVIDER_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
      - IDENTITY_AUTH_PROVIDER_BACKEND_URL=http://keycloak:18080/auth/realms/camunda-platform
      - IDENTITY_DATABASE_HOST=postgres
      - IDENTITY_DATABASE_PORT=5432
      - IDENTITY_DATABASE_NAME=bitnami_keycloak
      - IDENTITY_DATABASE_USERNAME=bn_keycloak
      - IDENTITY_DATABASE_PASSWORD=bitnami1234
    networks:
      - camunda-platform
    depends_on:
      - postgres
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    ports:
      - "18080:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/bitnami_keycloak
      - KC_DB_USERNAME=bn_keycloak
      - KC_DB_PASSWORD=bitnami1234
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/auth
    command: start-dev
    networks:
      - camunda-platform
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - camunda-platform

volumes:
  zeebe:
  operate_tmp:
  elasticsearch:
  postgres:

networks:
  camunda-platform: 