version: "3.9"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6001:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "6002:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  zeebe:
    image: camunda/zeebe:${CAMUNDA_ZEEBE_VERSION}
    environment:
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE=${ZEEBE_AUTHENTICATION_MODE}
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL=${KEYCLOAK_INTERNAL_REALM_URL}
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE=${IDENTITY_AUDIENCE}
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_BASEURL=${IDENTITY_INTERNAL_URL}
      - ZEEBE_BROKER_GATEWAY_MULTITENANCY_ENABLED=${MULTI_TENANCY_ENABLED}
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
    ports:
      - "6003:26500"

  operate:
    image: camunda/operate:${CAMUNDA_OPERATE_VERSION}
    environment:
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_IDENTITY_ISSUERBACKENDURL=${KEYCLOAK_EXTERNAL_REALM_URL}
      - CAMUNDA_IDENTITY_BASEURL=${IDENTITY_EXTERNAL_URL}
      - CAMUNDA_IDENTITY_AUDIENCE=${IDENTITY_AUDIENCE}
      - SPRING_PROFILES_ACTIVE=identity-auth
    ports:
      - "6004:8080"

  tasklist:
    image: camunda/tasklist:${CAMUNDA_TASKLIST_VERSION}
    environment:
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_IDENTITY_ISSUERBACKENDURL=${KEYCLOAK_EXTERNAL_REALM_URL}
      - CAMUNDA_IDENTITY_BASEURL=${IDENTITY_EXTERNAL_URL}
      - CAMUNDA_IDENTITY_AUDIENCE=${IDENTITY_AUDIENCE}
      - SPRING_PROFILES_ACTIVE=identity-auth
    ports:
      - "6005:8080"

  optimize:
    image: camunda/optimize:${CAMUNDA_OPTIMIZE_VERSION}
    environment:
      - CAMUNDA_OPTIMIZE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_IDENTITY_ISSUERBACKENDURL=${KEYCLOAK_EXTERNAL_REALM_URL}
      - CAMUNDA_IDENTITY_BASEURL=${IDENTITY_EXTERNAL_URL}
      - CAMUNDA_IDENTITY_AUDIENCE=${IDENTITY_AUDIENCE}
      - SPRING_PROFILES_ACTIVE=identity-auth
    ports:
      - "6006:8080"

  web-modeler-restapi:
    image: camunda/web-modeler-restapi:${CAMUNDA_WEB_MODELER_VERSION}
    environment:
      - CAMUNDA_IDENTITY_ISSUERBACKENDURL=${KEYCLOAK_EXTERNAL_REALM_URL}
      - CAMUNDA_IDENTITY_BASEURL=${IDENTITY_EXTERNAL_URL}
      - CAMUNDA_IDENTITY_AUDIENCE=${IDENTITY_AUDIENCE}
      - SPRING_PROFILES_ACTIVE=identity-auth
    ports:
      - "6007:8080"

  identity:
    image: camunda/identity:${CAMUNDA_IDENTITY_VERSION}
    environment:
      - IDENTITY_AUTH_PROVIDER=keycloak
      - KEYCLOAK_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=camunda-platform
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "6008:8084"

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_SERVER_VERSION}
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "6009:18080"
    depends_on:
      - postgres

  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION}
    ports:
      - "6010:8025"

volumes:
  postgres_data:
  es_data:
